# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# https://elanderson.net/2020/06/github-use-actions-to-run-multiple-jobs/

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  #first CI job
  build_backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install
        working-directory: backend

      - name: Build
        run: npm run build
        working-directory: backend